aspnet/DependencyInjection

src/Microsoft.Framework.DependencyInjection/ActivatorUtilities.cs
src/Microsoft.Framework.DependencyInjection/ObjectFactory.cs

Modify ActivatorUtilities.CreateFactory to return a delegate instead of a Func

---

src/Microsoft.Framework.DependencyInjection/ActivatorUtilities.cs
test/Microsoft.Framework.DependencyInjection.Tests/AllContainerTestsBase.cs
test/Microsoft.Framework.DependencyInjection.Tests/AutofacContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/NinjectContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/StructureMapContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/project.json

* Update Microsoft.Framework.DependencyInjection.Tests to run tests in
ASPENTCORE50
Fixes #170

* Specify Expression parameter type when building the factory expression

---

src/Microsoft.Framework.DependencyInjection.Autofac/project.json
src/Microsoft.Framework.DependencyInjection.Ninject/project.json
src/Microsoft.Framework.DependencyInjection.StructureMap/project.json
src/Microsoft.Framework.DependencyInjection.Unity/project.json
src/Microsoft.Framework.DependencyInjection.Windsor/project.json
src/Microsoft.Framework.DependencyInjection/project.json
test/Microsoft.Framework.DependencyInjection.Tests/project.json

Changed package versions to beta2

---

build.cmd
build.sh
src/Microsoft.Framework.DependencyInjection.Autofac/project.json
src/Microsoft.Framework.DependencyInjection.Interfaces/project.json
src/Microsoft.Framework.DependencyInjection.Ninject/project.json
src/Microsoft.Framework.DependencyInjection.StructureMap/project.json
src/Microsoft.Framework.DependencyInjection.Unity/project.json
src/Microsoft.Framework.DependencyInjection.Windsor/project.json
src/Microsoft.Framework.DependencyInjection/project.json
test/Microsoft.Framework.DependencyInjection.Tests/AllContainerTestsBase.cs
test/Microsoft.Framework.DependencyInjection.Tests/AutofacContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/NinjectContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/StructureMapContainerTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/project.json

Prepping to be merged once ready.

Update aspnet50/aspnetcore50 => dnx50/dnxcore50.

---

README.md

Entity Framework is on version 7, not 5. Also, Entity Framework looks better than EF imo.

Correct version for EF in README.md

---

src/Microsoft.Framework.DependencyInjection.Abstractions/ServiceProviderExtensions.cs
test/Microsoft.Framework.DependencyInjection.Tests/ServiceProviderExtensionsTest.cs

The non-generic GetRequiredServices wasn't actually checking if the service exists.

Bugfix for non-generic GetRequiredServices

---

src/Microsoft.Framework.DependencyInjection.Abstractions/Properties/Resources.Designer.cs
src/Microsoft.Framework.DependencyInjection.Abstractions/Resources.resx
src/Microsoft.Framework.DependencyInjection.Abstractions/ServiceCollectionExtensions.cs
src/Microsoft.Framework.DependencyInjection.Abstractions/ServiceDescriptor.cs
test/Microsoft.Framework.DependencyInjection.Tests/ServiceCollectionExtensionTest.cs

These changes will help make AddEntityFramework() idempotent
@rynowak This change removes the exception thrown by TryAddEnumerable, will this break any scenarios for MVC?
/cc @davidfowl

Add TryAddEnumerable overload and Add implementation factory overloads

---

test/Microsoft.Framework.DependencyInjection.Tests/ActivatorUtilitiesTests.cs
test/Microsoft.Framework.DependencyInjection.Tests/Fakes/DependsOnServiceWithoutImplementation.cs
test/Microsoft.Framework.DependencyInjection.Tests/Fakes/IServiceWithoutImplementation.cs
test/Microsoft.Framework.DependencyInjection.Tests/ServiceProviderContainerTests.cs

Adding unit tests for consuming services without implementations

---

src/Microsoft.Framework.DependencyInjection/ServiceProvider.cs
test/Microsoft.Framework.DependencyInjection.Tests/Fakes/ClassWithNestedReferencesToProvider.cs
test/Microsoft.Framework.DependencyInjection.Tests/Fakes/TestServices.cs
test/Microsoft.Framework.DependencyInjection.Tests/ScopingContainerTestBase.cs

Fix #292, bug introduced in bbb9acf101d4f9b3b818834c60572f67ec16ac63

Prevent Dispose from being called twice on ServiceProvider

---

README.md

Adding links to other DI container adapters

---

src/Microsoft.Extensions.DependencyInjection.Abstractions/Extensions/ServiceCollectionExtensions.cs
src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceDescriptor.cs
test/Microsoft.Extensions.DependencyInjection.Tests/ServiceCollectionExtensionTest.cs

Add TryAddSingleton that accepts an instance

---

.gitignore
.travis.yml
appveyor.yml
build.cmd
build.sh
test/Microsoft.Extensions.DependencyInjection.Tests/project.json

Build with dotnet

---

README.md

[DryIoc](https://bitbucket.org/dadhi/dryioc/overview) adapter. It passes DI.Spec.Tests.

Added DryIoc adapter to readme

---

src/Microsoft.Extensions.DependencyInjection.Abstractions/project.json
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/project.json
src/Microsoft.Extensions.DependencyInjection/project.json
test/Microsoft.Extensions.DependencyInjection.Tests/project.json

Remove netcore50

---

NuGetPackageVerifier.json
src/Microsoft.Extensions.DependencyInjection.Abstractions/project.json
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/project.json
src/Microsoft.Extensions.DependencyInjection/project.json

Enabled xml doc generation

---

src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs

Simplify codegen of scoped and singleton expressions

---

src/Microsoft.Extensions.DependencyInjection/ServiceProvider.cs

- Remove closure allocations from scoped services
/cc @rynowak

Fixed performance regression caused by c2e4406a81

---

src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/Fakes/FakeService.cs
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/Fakes/IFakeEveryService.cs
test/Microsoft.Extensions.DependencyInjection.Tests/CallSiteTests.cs

Use a non primtive type

---

src/Microsoft.Extensions.DependencyInjection.Abstractions/ISupportRequiredService.cs
src/Microsoft.Extensions.DependencyInjection.Abstractions/ServiceProviderExtensions.cs
test/Microsoft.Extensions.DependencyInjection.Tests/ServiceProviderExtensionsTest.cs

[Fixes ##378] Add interface to allow container implementors to expose a more native service lookup for required services
@davidfowl

Enable 3rd party DI containers to handle requests for required services.

---

.gitattributes
src/Microsoft.Extensions.DependencyInjection.Abstractions/project.json
src/Microsoft.Extensions.DependencyInjection/project.json

Part of https://github.com/aspnet/EntityFramework/pull/5021

Cross-compile to netcore50 to support EF on UWP

---

test/Microsoft.Extensions.DependencyInjection.Tests/project.json

Migrate tests/samples/tools to portable

---

README.md

adding Grace

---

src/Microsoft.Extensions.DependencyInjection.Specification.Tests/project.json
test/Microsoft.Extensions.DependencyInjection.Tests/project.json

Updating to RTM builds of xunit

---

README.md

added: Note about package rename.

Updated readme link to DryIoc RTM adapter.

---

src/Microsoft.Extensions.DependencyInjection.Abstractions/project.json

https://github.com/aspnet/DependencyInjection/issues/420
@NTaylorMullen @Eilon

Removed description in project.json from DI Abstractions

---

src/Microsoft.Extensions.DependencyInjection.Specification.Tests/ActivatorUtilitiesTests.cs
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/ServiceCollection.cs

Rename ServiceCollection in the test specification to TestServiceCollection

---

README.md

Hi! In this PR i have added my dependency injection container to the external container list in the README.md, it passes the Spec.Tests, repo: https://github.com/z4kn4fein/stashbox-extensions-dependencyinjection

Added Stashbox to the external container list

---

src/Microsoft.Extensions.DependencyInjection/breakingchanges.netcore.json
src/Microsoft.Extensions.DependencyInjection/exceptions.netcore.json

React to aspnet/BuildTools#238

Update API Check related files

---

build/common.props
build/dependencies.props
src/Microsoft.Extensions.DependencyInjection.Abstractions/Microsoft.Extensions.DependencyInjection.Abstractions.csproj
src/Microsoft.Extensions.DependencyInjection.Specification.Tests/Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj
src/Microsoft.Extensions.DependencyInjection/Microsoft.Extensions.DependencyInjection.csproj

Target .NET Standard 2.0

---

src/Microsoft.Extensions.DependencyInjection/ServiceLookup/ConstructorCallSite.cs
src/Microsoft.Extensions.DependencyInjection/ServiceLookup/FactoryCallSite.cs
test/Microsoft.Extensions.DependencyInjection.Tests/CallSiteTests.cs

Fix ImplementationType of ConstructorCallSite and FactoryCallSite

---

README.md

Please add Unity to the list of compatible containers

Unity added support for Microsoft.Extensions.DependencyInjection

---

src/DI.Abstractions/Extensions/ServiceCollectionDescriptorExtensions.cs
src/DI/ServiceCollectionContainerBuilderExtensions.cs
src/DI/ServiceLookup/Expressions/ExpressionResolverBuilder.cs

Ello,
Mostly fixed some typos and spelling errors in XML doc comments and source.
Going for a nice t-shirt. Finally, my last PR!
Happy #Hacktoberfest :smiley_cat: :fearful: :skull_and_crossbones: :moon: :bat: 
Thanks,
Brian
:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**

Typos/spelling errors in XML doc comments and source. #Hacktoberfest
